'use client'
/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.2 buddha.glb --transform 
Files: buddha.glb [9.9MB] > /Users/genesis/next-project/portfolio/public/gltf/buddha-transformed.glb [1.32MB] (87%)
Author: Cleveland Museum of Art (https://sketchfab.com/clevelandart)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/195086-buddha-of-the-future-miroku-bosatsu-60c29a8c17404a6091342637987e2713
Title: 1950.86 Buddha of the Future (Miroku Bosatsu)
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'
export function BuddhaModel({ ...props }) {
  const { nodes, materials } = useGLTF('/gltf/buddha-transformed.glb')
  return (
    <group {...props} dispose={null} scale={[6, 6, 6]}>
      {/* <mesh geometry={nodes.Object_2.geometry} material={materials['1950.86_Buddha_of_the_Future_Mats']} rotation={[-Math.PI / 2, 0, Math.PI / 2]} /> */}
    </group>
  )
}

useGLTF.preload('/gltf/buddha-transformed.glb')
