'use client'

/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.2 buddha-transformed.glb -t 
Author: Cleveland Museum of Art (https://sketchfab.com/clevelandart)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/195086-buddha-of-the-future-miroku-bosatsu-60c29a8c17404a6091342637987e2713
Title: 1950.86 Buddha of the Future (Miroku Bosatsu)
*/

import * as THREE from 'three'
import React from 'react'
import { useGLTF } from '@react-three/drei'
import { GLTF } from 'three-stdlib'

type GLTFResult = GLTF & {
  nodes: {
    Object_2: THREE.Mesh
  }
  materials: {
    ['1950.86_Buddha_of_the_Future_Mats']: THREE.MeshStandardMaterial
  }
}

export default function Model(props: JSX.IntrinsicElements['group']) {
  const { nodes, materials } = useGLTF('/gltf/buddha-transformed.glb') as GLTFResult
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Object_2.geometry} material={materials['1950.86_Buddha_of_the_Future_Mats']} rotation={[-Math.PI / 2, 0, Math.PI / 2]} />
    </group>
  )
}

useGLTF.preload('/gltf/buddha-transformed.glb')
